
frontend:
	@sh Components/frontend.sh

#mongodb:
#	@sh mongodb.sh

#catalogue:
#	@sh catalogue.sh

#redis:
#	@sh redis.sh

#user:
#	@sh user.sh

#cart:
#	@sh cart.sh

#mysql:
#	@sh mysql.sh

#shipping:
#	@sh shipping.sh

#payment:
#	@sh payment.sh

